create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references auth.users (id) on delete cascade,
  referred_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists referrals_unique_referred_id on public.referrals (referred_id);
create index if not exists referrals_referrer_id_idx on public.referrals (referrer_id);

alter table public.referrals enable row level security;

drop function if exists public.record_referral(uuid);
create function public.record_referral(referrer_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  referred uuid := auth.uid();
  inserted boolean := false;
begin
  if referred is null then
    return false;
  end if;

  if referrer_id is null then
    return false;
  end if;

  if referrer_id = referred then
    return false;
  end if;

  if not exists (select 1 from auth.users u where u.id = referrer_id) then
    return false;
  end if;

  insert into public.referrals (referrer_id, referred_id)
  values (referrer_id, referred)
  on conflict (referred_id) do nothing;

  get diagnostics inserted = row_count;
  return inserted;
end;
$$;

revoke all on function public.record_referral(uuid) from public;
grant execute on function public.record_referral(uuid) to authenticated;

drop function if exists public.get_my_referral_count();
create function public.get_my_referral_count()
returns integer
language sql
security definer
set search_path = public
as $$
  select count(*)::int from public.referrals r where r.referrer_id = auth.uid();
$$;

revoke all on function public.get_my_referral_count() from public;
grant execute on function public.get_my_referral_count() to authenticated;

drop function if exists public.resolve_referrer_id_from_tag(text);
create function public.resolve_referrer_id_from_tag(tag text)
returns uuid
language sql
security definer
set search_path = public
as $$
  select p.id from public.profiles p where lower(p.tag) = lower(tag) limit 1;
$$;

revoke all on function public.resolve_referrer_id_from_tag(text) from public;
grant execute on function public.resolve_referrer_id_from_tag(text) to authenticated;
